@startuml

enum MessageType {
    ERROR
    SUCCESS
}

class Message {
    +messageText: String
    +messageType: MessageType
}

class CommandParser {
    -commandMap: Map<String, Command>
    +parseCommand(commandName: String): Command
}

class FileSystemEngine {
    -rootDirectory: Directory
    +startConsole()
}

class Console {
    -actualDir: Directory
    -commandParser: CommandParser
    -executeCommand()
    +readCommand(): Message
}

interface Command {
    +execute()
}

class LsCommand implements Command {
    +execute()
}

interface FileType {
}

class Directory implements FileType{
    -contents: List<File>
    +add(FileType)
    +remove(FileType)
}

Directory *-- FileType

class File implements FileType{
    -name: String
    -path: String
    +getName()
    +getPath()
}

@enduml